<?php
$WIN32_SVC_ERRORS = array(
    WIN32_ERROR_ACCESS_DENIED				        => "The handle to the SCM database does not have the appropriate access rights.",
    WIN32_ERROR_CIRCULAR_DEPENDENCY			        => "A circular service dependency was specified.",
    WIN32_ERROR_DATABASE_DOES_NOT_EXIST				=> "The specified database does not exist.",
    WIN32_ERROR_DEPENDENT_SERVICES_RUNNING			=> "The service cannot be stopped because other running services are dependent on it.",
    WIN32_ERROR_DUPLICATE_SERVICE_NAME				=> "The display name already exists in the service control manager database either as a service name or as another display name.",
    WIN32_ERROR_FAILED_SERVICE_CONTROLLER_CONNECT   => "This error is returned if the program is being run as a console application rather than as a service. If the program will be run as a console application for debugging purposes, structure it such that service-specific code is not called.",
    WIN32_ERROR_INSUFFICIENT_BUFFER					=> "The buffer is too small for the service status structure. Nothing was written to the structure.",
    WIN32_ERROR_INVALID_DATA						=> "The specified service status structure is invalid.",
    WIN32_ERROR_INVALID_HANDLE						=> "The handle to the specified service control manager database is invalid.",
    WIN32_ERROR_INVALID_LEVEL						=> "The InfoLevel parameter contains an unsupported value.",
    WIN32_ERROR_INVALID_NAME						=> "The specified service name is invalid.",
    WIN32_ERROR_INVALID_PARAMETER					=> "A parameter that was specified is invalid.",
    WIN32_ERROR_INVALID_SERVICE_ACCOUNT				=> "The user account name specified in the user parameter does not exist",
    WIN32_ERROR_INVALID_SERVICE_CONTROL			    => "The requested control code is not valid, or it is unacceptable to the service.",
    WIN32_ERROR_PATH_NOT_FOUND						=> "The service binary file could not be found.",
    WIN32_ERROR_SERVICE_ALREADY_RUNNING				=> "An instance of the service is already running.",
    WIN32_ERROR_SERVICE_CANNOT_ACCEPT_CTRL			=> "The requested control code cannot be sent to the service because the state of the service is WIN32_SERVICE_STOPPED, WIN32_SERVICE_START_PENDING, or WIN32_SERVICE_STOP_PENDING.",
    WIN32_ERROR_SERVICE_DATABASE_LOCKED				=> "The database is locked.",
    WIN32_ERROR_SERVICE_DEPENDENCY_DELETED			=> "The service depends on a service that does not exist or has been marked for deletion.",
    WIN32_ERROR_SERVICE_DEPENDENCY_FAIL				=> "The service depends on another service that has failed to start.",
    WIN32_ERROR_SERVICE_DISABLED					=> "The service has been disabled.",
    WIN32_ERROR_SERVICE_DOES_NOT_EXIST				=> "The specified service does not exist as an installed service.",
    WIN32_ERROR_SERVICE_EXISTS						=> "The specified service already exists in this database.",
    WIN32_ERROR_SERVICE_LOGON_FAILED				=> "The service did not start due to a logon failure. This error occurs if the service is configured to run under an account that does not have the \"Log on as a service\" right.",
    WIN32_ERROR_SERVICE_MARKED_FOR_DELETE			=> "The specified service has already been marked for deletion.",
    WIN32_ERROR_SERVICE_NO_THREAD					=> "A thread could not be created for the service.",
    WIN32_ERROR_SERVICE_NOT_ACTIVE					=> "The service has not been started.",
    WIN32_ERROR_SERVICE_REQUEST_TIMEOUT				=> "The process for the service was started, but it did not call StartServiceCtrlDispatcher, or the thread that called StartServiceCtrlDispatcher may be blocked in a control handler function.",
    WIN32_ERROR_SHUTDOWN_IN_PROGRESS				=> "The system is shutting down; this function cannot be called.",
    WIN32_NO_ERROR								    => "No error."
);
?>